## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np

In [4]:

arr1=np.array([[1,2,3]
              ,[4,5,6]
              ,[7,8,9]])

arr2=np.array([[10,20,3]
              ,[4,5,6]
              ,[7,8,9]])

arr3=arr1*arr2
print(arr3)



[[10 40  9]
 [16 25 36]
 [49 64 81]]


## Write a NumPy program to compute the determinant of a given square array

In [7]:
arr4=np.linalg.det(arr2)
print(arr4)

81.0000000000001


## Write a NumPy program to compute the cross product of two given vectors

In [9]:
arr5=arr1.dot(arr2)
print(arr5)

[[ 39  54  42]
 [102 153  96]
 [165 252 150]]


## Write a NumPy program to compute the condition number of a given matrix

In [ ]:
#didn't take it in session

## Write a NumPy program to compute the inverse of a given matrix

In [10]:
arr7=np.linalg.inv(arr2)
print(arr7)

[[-0.03703704 -1.92592593  1.2962963 ]
 [ 0.07407407  0.85185185 -0.59259259]
 [-0.03703704  0.74074074 -0.37037037]]
